// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGAt8HYAx1rc18Z2e9mlIFinlajQyIK4',
    appId: '1:1095033962890:web:04c7d6bd9bb5f3f6f74873',
    messagingSenderId: '1095033962890',
    projectId: 'usapho-dashboard',
    authDomain: 'usapho-dashboard.firebaseapp.com',
    storageBucket: 'usapho-dashboard.firebasestorage.app',
    measurementId: 'G-W856KT5RQD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWCOEo_ZFB87m-0sSOA9HyyKhrrSsGbA',
    appId: '1:1095033962890:android:265bb30ef260a2f0f74873',
    messagingSenderId: '1095033962890',
    projectId: 'usapho-dashboard',
    storageBucket: 'usapho-dashboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqu-crDp_SWjz-mJkIqR7S9x8ZrcfEo4g',
    appId: '1:1095033962890:ios:353706c696ff207ff74873',
    messagingSenderId: '1095033962890',
    projectId: 'usapho-dashboard',
    storageBucket: 'usapho-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.usaphoDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqu-crDp_SWjz-mJkIqR7S9x8ZrcfEo4g',
    appId: '1:1095033962890:ios:353706c696ff207ff74873',
    messagingSenderId: '1095033962890',
    projectId: 'usapho-dashboard',
    storageBucket: 'usapho-dashboard.firebasestorage.app',
    iosBundleId: 'com.example.usaphoDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApGAt8HYAx1rc18Z2e9mlIFinlajQyIK4',
    appId: '1:1095033962890:web:5ebb8841c63a6f26f74873',
    messagingSenderId: '1095033962890',
    projectId: 'usapho-dashboard',
    authDomain: 'usapho-dashboard.firebaseapp.com',
    storageBucket: 'usapho-dashboard.firebasestorage.app',
    measurementId: 'G-79PKSEGWGF',
  );
}
